version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - API_KEY=thoovara@hari
    volumes:
      - ./backend/app/database:/app/app/database
      - ./backend/logs:/app/logs
    networks:
      - local-ai-network
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    networks:
      - local-ai-network
    depends_on:
      - backend

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - local-ai-network
    environment:
      - OLLAMA_HOST=0.0.0.0:11434

volumes:
  ollama_data:

networks:
  local-ai-network:
    driver: bridge
